DROP TABLE "User" CASCADE;
DROP TABLE User_photo CASCADE;
DROP TABLE Fixed_interest CASCADE;
DROP TABLE Interest CASCADE;
DROP TABLE "Match" CASCADE;
DROP TABLE Fixed_requirement CASCADE;
DROP TABLE Requirement CASCADE;